### ISSUE TITLE
Script stops due to invalid character '\x00'

### ISSUE THREAD

**Issue by mate71pl** [tcivie/meshtastic-metrics-exporter#69]
The script stops updating metrics, and the following error appears:
```
error from daemon in stream: Error grabbing logs: invalid character '\x00' looking for beginning of value
```
Docker container still appears healthy and does not restart, yet the metrics stop updating.
More from docker journalctl:
```
Nov 01 19:53:33 docker dockerd[894]: time="2024-11-01T19:53:33.315915636Z" level=error msg="Error streaming logs: invalid character '\\x00' looking for beginning of value" container=1a46a68472a19ae5a310f735df70c7bcc07cf9ce4453f1a2ce594d699a6c1a70 method="(*Daemon).ContainerLogs" module=daemon spanID=2c8f04acba25b098 traceID=e1d09c567889e3466dceb30ea6cef6c1
Nov 01 19:58:05 docker dockerd[894]: time="2024-11-01T19:58:05.631945453Z" level=error msg="stream copy error: reading from a closed fifo"
Nov 01 19:58:05 docker dockerd[894]: time="2024-11-01T19:58:05.639607994Z" level=error msg="Error running exec 9440faafb1f0ca243c7f52cc6d1d5550d37d3429fe460d4068ae97d493508738 in container: OCI runtime exec failed: exec failed: unable to start container process: exec: \"/bin/bash\": stat /bin/bash: no such file or directory: unknown" spanID=266cb48ab5fbbf21 traceID=5d6211fde9bfaf99f88eefc69d4685a6
Nov 01 19:58:05 docker dockerd[894]: time="2024-11-01T19:58:05.644466592Z" level=error msg="failed to close container stdin" container=1a46a68472a19ae5a310f735df70c7bcc07cf9ce4453f1a2ce594d699a6c1a70 error="NotFound: process does not exist 9440faafb1f0ca243c7f52cc6d1d5550d37d3429fe460d4068ae97d493508738: not found" module=libcontainerd namespace=moby
Nov 01 19:59:04 docker dockerd[894]: time="2024-11-01T19:59:04.349281791Z" level=error msg="Error streaming logs: invalid character '\\x00' looking for beginning of value" container=1a46a68472a19ae5a310f735df70c7bcc07cf9ce4453f1a2ce594d699a6c1a70 method="(*Daemon).ContainerLogs" module=daemon spanID=2fe3c66b9c3cd286 traceID=f53ed40145378143b654839b9d64bb20
```

Unfortunately, the situation where a Python script stops but still appears healthy is quite common. You can take a look at how I solved it on my end. It's a more basic version of your solution, which, unfortunately, I hadn’t thought of earlier, so I started to tinker on my own :) https://github.com/mate71pl/meshprom. In my solution, metrics are gathered from two virtual nodes connected to two different MQTT servers: one official public server and another one hosted by me.

If you’d like to check out the statistics I’ve collected, feel free to visit: https://stats.loramesh.pl/
```
Login: ******
Hasło: ******
```
I will gradually transform my current solution mostly to follow yours as time and resources allow.

By the way, I'd like to congratulate you on a fantastic job! :)

**Comment by tcivie** [comment]
Hey @mate71pl, thanks for the update.

Could you please provide more details about where you encountered the error? 
`error from daemon in stream: Error grabbing logs: invalid character ‘\x00’ looking for beginning of value.`
Was it originating from the exported pod or somewhere else?

I checked our community server for any similar errors and couldn’t find anything. Based on the error message, it seems like there might have been a connectivity issue that caused this bug. Typically, such issues would result in the exporter restarting, which should hopefully reconnect to the server.

Also if you have any improvement suggestions you can feel free to fork this project, make the changes and then open a pull request 🙂

---
P.S. Your dashboard looks fantastic! I’ve removed the credentials from your post so that others won’t accidentally cause any issues.

**Comment by mate71pl** [comment]
Hi @tcivie, thank you for your quick answer!
The error was found in `docker logs mesh-metrics`, and at the time it occurred, it halted the metrics update. After a restart, the metrics are gathering correctly again, but now when I try to view the logs, the display stops at the same point. However, if I view only the last few logs with the -n 10 flag, I can see they are still accumulating. There’s probably an issue with UTF-8 character encoding. I’ll try to look into it further.

```
$ docker logs meshtastic-metrics-exporter
....
2024-10-29T14:39:41.426767391Z Received message on topic 'msh/PL/2/e/LongFast/!7c5ad274' at 2024-10-29 14:39:41
2024-10-29T14:39:50.805710461Z Received message on topic 'msh/PL/2/stat/!05f5e0fb' at 2024-10-29 14:39:50
2024-10-29T14:39:50.898532499Z Received message on topic 'msh/PL/2/stat/!05f5e0fb' at 2024-10-29 14:39:50
error from daemon in stream: Error grabbing logs: invalid character '\x00' looking for beginning of value
```
```
$ docker logs meshtastic-metrics-exporter -n 10
Received message on topic 'msh/pl/2/e/LongFast/!c0c31248' at 2024-11-02 11:17:54
Received message on topic 'msh/2/stat/!75e19a4c' at 2024-11-02 11:17:55
Received message on topic 'msh/2/stat/!75e19a4c' at 2024-11-02 11:17:55
Received message on topic 'msh/pl/2/e/LongFast/!c0c31248' at 2024-11-02 11:18:00
Received message on topic 'msh/pl/2/e/PKI/!c0c31248' at 2024-11-02 11:18:00
Failed to decrypt message: Unexpected end-group tag.
Received message on topic 'msh/pl/2/e/LongFast/!c0c31248' at 2024-11-02 11:18:13
Received message on topic 'msh/pl/2/e/LongFast/!c0c31248' at 2024-11-02 11:18:14
Received message on topic 'msh/pl/2/e/PKI/!c0c31248' at 2024-11-02 11:18:15
Failed to decrypt message: Unexpected end-group tag.
```

When I check now using curl, I can see that emojis in node names and Polish characters are displayed incorrectly, e.g., `Long name <F0><9F>` instead of `Long name 🛜`. I’ll try to fix this and we’ll see if the issue still persists.

P.S.
As for the Grafana password is publicly available, mainly added as an extra safeguard against bots, but thank you for your concern :)

**Comment by tcivie** [comment]
Hey @mate71pl, That's an interesting point.

I’m aware that emojis in node names are handled correctly on our server. However, in cases involving rare characters like Polish ones, it’s possible that this issue is the culprit.

In this section of the code,  I’ve hardcoded the decoding of the payload to UTF-8:
https://github.com/tcivie/meshtastic-metrics-exporter/blob/c187380bf2c0d5ccf4f27aa7d85a927e33644b9f/main.py#L58-L67

We should investigate if there’s a way to dynamically decode the payload.

---
Additionally, keep in mind that if you’re retrieving data from the public MQTT server, there’s a higher likelihood that it may contain junk or experimental packets that aren’t compatible with the current Proto structure.

**Comment by mate71pl** [comment]
I’m not using the official MQTT, but there are quite a few people on this one too, so maybe someone is testing something.
Today, when I checked the dashboard, I noticed that metrics haven't updated since yesterday. Checking via `docker logs`, it looked like they were updating normally, with entries showing the current date and time. After further investigation, examining the time on the graph when it stopped updating, I found the following in the logs:
```
Failed to process message: column "range_test_packets_total" is of type integer but expression is of type timestamp with time zone
LINE 8:                 ) VALUES ($1, $2, NOW(), NOW(), NOW())
                                          ^
HINT:  You will need to rewrite or cast the expression.
```

I’ll keep an eye on the issue as soon as I find some time.

I also saw the following messages, but they likely didn’t cause any issues:
```
Failed to decrypt message: Unexpected end-group tag.
```

```
Failed to decrypt message: Field number 0 is illegal.
```

**Comment by tcivie** [comment]
The issue has been stale for a month. If the issue would arrise again feel free to comment on it again.
