### ISSUE TITLE
Many unknown nodes

### ISSUE THREAD

**Issue by ragnarblackmane** [tcivie/meshtastic-metrics-exporter#74]
**Describe the bug**
MQTT status shows "Unknown" (even for the node directly connected to MQTT.
Almost any node (except the ones in my home) are "Unknown".
Every node (mine and the others, some getting here from another MQTT gateway in my home and some through lora) are on MediumFast with the default key (AQ==).

**Expected behavior**
Should see more info for the nodes (as shown in the android app).

Question: maybe it's something wrong on my configuration?
Should I enable or disable encryption in MQTT? (i don't mean TLS, just the encryption option).
In the .env file I've left the default key.

**Comment by tcivie** [comment]
Hi @ragnarblackmane,
This is actually expected behavior - there's nothing wrong with your setup. Here's what's happening:
The "Unknown" status occurs because the MQTT exporter hasn't received a NodeInfo packet from those specific nodes yet. The exporter works by gradually building up information about each node as it receives different types of packets:

1. When a node first appears, it starts with minimal information, showing as "Unknown" 
2. As NodeInfo packets arrive, the exporter fills in additional details about the node
3. Over time, the "Unknown" status will be replaced with more complete information

This explains why you see more detailed information in the Android app - it's likely been running longer and has accumulated more NodeInfo packets from the nodes.

Regarding encryption: The default encryption key (AQ==) is fine, and toggling MQTT encryption won't affect this behavior. This is purely related to the NodeInfo packet reception process.

Let me know if you have any other questions! I'm happy to clarify further.
